### ISSUE TITLE
Missing vacuum in the materials database

### ISSUE THREAD

**Issue by EustacheG** [chernals/georges#30]
![vacuum missing](https://user-images.githubusercontent.com/32551680/55254147-69130f80-5257-11e9-84bc-745ad59090f5.png)

Error when calling compute_fermi_eyges (the low level function is get_range_from_energy)

**Comment by chernals** [comment]
@EustacheG Can you share a [minimal example](https://stackoverflow.com/help/mcve) to reproduce the issue ?

**Comment by chernals** [comment]
Bug invalid; that's not supposed to work, a direct call to a material that doesn't exists is not valid.

However, it should be possible to specify vacuum in higher level functions. Open another issue if that doesn't work either.
